import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { SubHeading } from "../components";
import images from "../constants/images";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-black text-white flex flex-col sm:flex-row justify-between items-center min-h-screen py-16 px-8 sm:p-16 md:py-16 md:px-24">
        <div className="flex flex-1 w-full justify-center items-start flex-col">
          <SubHeading title="Chase the new flavour" />
          <h1 className="text-golden tracking-wide font-base capitalize font-bold text-4xl sm:text-7xl lg:text-8xl">
            The key to Fine Dining
          </h1>
          <p className="my-8 mx-0 font-normal capitalize text-base">
            Sit tellus lobortis sed senectus vivamus molestie. Condimentum
            volutpat morbi facilisis quam scelerisque sapien. Et, penatibus
            aliquam amet tellus
          </p>
          <button type="button" className="text-black bg-crimson font-['Cormorant_Upright'] font-bold text-base py-2 px-6 rounded-sm border-0 outline-none cursor-pointer">
            Explore Menu
          </button>
        </div>
        <div className="flex flex-1 w-full justify-center items-center ml-0 mt-8 sm:mt-0 sm:ml-8">
          <div className="w-[80%]">
          <Image src={images.welcome} alt="welcome"/>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
